[package]
name = "arbitra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
yew-router = "0.15.0"
anyhow = "1.0.42"
serde = { version = "1.0", features = ["derive"]}
yewdux = "^0.6"
serde_json = "1.0.93"
http = "0.2.1"
wasm-bindgen = "0.2"
js-sys = "0.3.63"


[dependencies.web-sys]
version = "0.3"
features = ["FormData", "XmlHttpRequest"]